development:
  superfeedr:
    login: login@superfeedr.com
    password: pass
production:
  superfeedr:
    login: login@superfeedr.com
    password: pass
test:
  superfeedr:
    login: login@superfeedr.com
    password: pass
